version: '3'
services:
  java:
    image: mcr.microsoft.com/devcontainers/base:bullseye
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - .:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 8080:8080
      - 8081:8081
    expose:
      - 8080
      - 8081
